export const NAV_LINKS = [
  {
    href: "/store",
    label: "Store",
  },
  {
    href: "#men's clothing",
    label: "Men's",
    elementId: "men's clothing",
  },
  {
    href: "#women's clothing",
    label: "Women's",
    elementId: "women's clothing",
  },
  {
    href: "#jewelries",
    label: "Jewelries",
    elementId: "jewelries",
  },
  {
    href: "#electronics",
    label: "Electronics",
    elementId: "electronics",
  },
];

export const CATEGORIES = [
  "men's clothing",
  "women's clothing",
  "jewelries",
  "electronics",
];

export const PRODUCT_IMAGES = [
  {
    id: 1,
    images: [
      "https://m.media-amazon.com/images/I/917S3ymUnNL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91Z6iJ-4+OL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71OLyG4oHdL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71T2PUNPndL._AC_SL1500_.jpg",
    ],

    details: [
      "65% Polyester, 35% Cotton",
      "Imported",
      "Simple functional backpack in G-1000 HeavyDuty Eco.",
      "Top folds down and is attached with textile straps and metal buckles.",
      "Inside pocket with padded base for laptop.",
      "Zippered front pocket.",
    ],
  },
  {
    id: 2,
    images: [
      "https://m.media-amazon.com/images/I/71dC1+6WdZL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71dCLH4kk+L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71v0lr2yEwL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61DCdZYi78L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71NyZBj16US._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61tO+6xx8QL._AC_SL1500_.jpg",
    ],
    details: [
      "Style no : #CMTTL077- Cotton Blended Long Raglan Sleeves",
      "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
      "Great for Daily and Casual Wear, High Softness & Wearability.",
      "Fit & Size : Slim Fit, Review Our Size Chart In Description",
      "Garment Care: Hand Wash Recommended / Machine Wash Cold,Tumble Dry Low With Care",
    ],
  },
  {
    id: 3,
    images: [
      "https://m.media-amazon.com/images/I/71li-ujtlUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61S6cxYewdL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71sPbgcSyUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/710--wuonoL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/619HCg+gWsL._AC_SL1500_.jpg",
    ],
    details: [
      "Slim fit shell jackets designed in classic style and the drawstring waist design makes it convenient to adjust to your ultimate comfortable fit.",
      "This casual cotton thick jacket with stand collar and full-up zipper closure effectively blocks strong wind or cold air and keeps you warm in the fall and early winter days.",
      "Breathable and Soft: the cotton fabric provides soft-wearing comfort and medium weight, perfect for daily wear.",
      "Multi-pockets: 3 deep outside pockets with large capacity and 1 inner pocket, very useful for put your hands comfortable and carry your phone,keys, tools at the same time.",
      "Occasions: great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
    ],
  },
  {
    id: 4,
    images: [
      "https://m.media-amazon.com/images/I/71oeb7JGYTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/713Fdpls1OL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81C70bflFVL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/511KE1d43zL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71iePpon80L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61BnS7B5JYL._AC_SL1500_.jpg",
    ],
    details: [
      "Style no : #CMTTL137 - Crew Neck Long Sleeve Basic T-shirt",
      "Crew neck Pullover",
      "Soft Cotton Blended Knit T-Shirts",
      "This Crew Neck T-shirt is engineered from a premium cotton blend for super soft & comfort. These long sleeve T-shirts are lightweight, breathable, and have a modern fit that's tailored to look good on all body types.",
      "",
    ],
  },
  {
    id: 5,
    images: [
      "https://m.media-amazon.com/images/I/61ibX4qwYnL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61VOAiXOi8L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81OwsqFAPXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71MjO+pw7oL._AC_SL1500_.jpg",
    ],
    details: [
      "STERLING SILVER: A legendary symbol of love, protection and prosperity. Cast and carved entirely by hand. From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
      "ARTISAN CRAFTED:Born in Bali out of an artisan community. A mix of modern design and traditional craft. Handcrafted and perfectly imperfect. Sustainably minded from the very beginning, with a connection to nature. We are artisan handcrafted jewelry unlike any other.",
      "CERTIFIED AUTHENTIC: Each piece is certified authentic John Hardy and comes stamped with a unique artisan signature ensuring the quality of each piece.",
      "THE PERFECT FIT: The perfect fit does exist–Bracelet measures 5MM. Small fits 5.5-6.0 inch wrist, Medium fits 6.0-6.5 inch wrist, Large fits 6.5-7.0 inch wrist",
      "ICONIC SINCE 1975: For over four decades, we've woven chains by hand using 100% reclaimed precious metals and ethically sourced gemstones. We are a proud member of the Responsible Jewellery Council.",
    ],
  },
  {
    id: 6,
    images: ["https://m.media-amazon.com/images/I/615ZzOEVEaL._AC_SL1500_.jpg"],
    details: [
      "Metal: 14K Solid Gold, High Polished Finish, Nickel Free. Metal Stamp 14K.",
      "Micropave with 19pcs round brilliant cut moissanite.",
      "All moissanites for this wedding ring are G-H Color, VVS1-VVS2, ideal cut.",
      "About 2mm width band.",
      "Elegant, velvet ring box included with each purchase.",
    ],
  },
  {
    id: 7,
    images: [
      "https://m.media-amazon.com/images/I/71YAIFU48IL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/617vzlQQT0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61haR1ygELL._AC_SL1500_.jpg",
    ],
    details: [
      "Pretty AAA+ CZ crystal and 18k gold plated Last a long time",
      "Best Fashion Jewelry Promise Anniversary Princess Ring for Women",
      "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her",
      "Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
    ],
  },
  {
    id: 8,
    images: [
      "https://m.media-amazon.com/images/I/51UDEzMJVpL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/612WTpgsUQL._AC_SL1500_.jpg",
    ],
    details: [
      "Rose Gold Plated Double Flared Tunnel Plug Earrings",
      "Made of 316L Stainless Steel",
      "Available in Sizes from 3mm (8GA) to 25mm (1 inch)",
      "Double Flared for a Comfortable Fit",
      "Sold as a Pair",
    ],
  },
  {
    id: 9,
    images: [
      "https://m.media-amazon.com/images/I/41fJs1xw6bL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51yOX-hmPqL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61t6Ng03JiL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51RUgyzYVfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/610hYncWy+L._AC_SL1500_.jpg",
    ],
    details: [
      "High capacity in a small enclosure – The small, lightweight design offers up to 6TB* capacity, making WD Elements portable hard drives the ideal companion for consumers on the go.",
      "Plug-and-play expandability",
      "Vast capacities up to 6TB[1] to store your photos, videos, music, important documents and more",
      "SuperSpeed USB 3.2 Gen 1 (5Gbps)",
    ],
  },
  {
    id: 10,
    images: [
      "https://m.media-amazon.com/images/I/61P39LA75pL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61vX3Yn9mAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61mExYRV6mL._AC_SL1500_.jpg",
    ],
    details: [
      "Easy upgrade for faster boot-up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive. Based on published specifications and internal benchmarking tests using PCMark Vantage scores.).Specific uses: Business, personal",
      "Boosts burst write performance, making it ideal for typical PC workloads",
      "The perfect balance of performance and reliability",
      "Read/write speeds of up to 535MB/s/350MBs (Based on read speed; write speed lower. Based on internal testing; performance may vary depending upon drive capacity, interface host device, OS and application. 1MB=1,000,000 bytes.)",
      "Shock-resistant for proven durability—even if you drop your computer (Shock resistant (up to 1500G) and vibration resistant (5gRMS, 10-2000 HZ/4.9 gRMS, 7-800 HZ), Temperature (from 0 degrees C to 70 degrees))",
    ],
  },
  {
    id: 11,
    images: [
      "https://m.media-amazon.com/images/I/71fPaBb0-YL._AC_SL1500_PIbundle-2,TopRight,0,0_SH20_.jpg",
      "https://m.media-amazon.com/images/I/81SIJRoPR8L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Pgqotwl9L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ate1YmEyL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71d313WigOL._AC_SL1500_.jpg",
    ],
    details: [
      "3D NAND flash are applied to deliver high transfer speeds",
      "Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan",
      "7mm slim design suitable for Ultrabooks and Ultra-slim notebooks.",
      "3-year limited warranty. (Please register your product via SP official website to get the complete manufacturer warranty services, product support and more.)",
    ],
  },
  {
    id: 12,
    images: [
      "https://m.media-amazon.com/images/I/614kExSCswL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/611O2r8-47L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61+lPq4Cu+L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61wwtSvK01L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51oNXJJRAOL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81f8-kNX3fL._AC_SL1500_.jpg",
    ],
    details: [
      "Expand your PS4 gaming experience",
      "Play anywhere",
      "Fast and easy setup",
      "Sleek design with high capacity",
    ],
  },
  {
    id: 13,
    images: [
      "https://m.media-amazon.com/images/I/81QpkIctqPL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71GbO41HbYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71xb7GDuAGL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51A1kQvFNaL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51tuEFDaPhL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61zhZdddWVL._AC_SL1500_.jpg",
    ],
    details: [
      "21.5 inches Full HD (1920 x 1080) widescreen IPS display.Specific uses for product - Business, personal",
      "And Radeon free sync technology. No compatibility for VESA Mount",
      "Refresh rate: 75 hertz - Using HDMI port",
      "Zero-frame design; Ultra-thin; 4ms response time; IPS panel",
      "Ports: 1 x HDMI & 1 x VGA",
      "Aspect ratio - 16:9. Color supported - 16.7 million colors. Brightness - 250 nit",
      "Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree",
      "75 hertz",
    ],
  },
  {
    id: 14,
    images: [
      "https://m.media-amazon.com/images/I/81Butfqtj5L.__AC_SY300_SX300_QL70_FMwebp_.jpg",
      "https://m.media-amazon.com/images/I/81WtAdXLjJL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/812Ri9cjUcL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/711uu1wZZ9L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/714xeshAy2L._AC_SL1500_.jpg",
    ],
    details: [
      "49-Inch monitor with super ultra-wide 49-inch screen with its innovative 32: 9 aspect ratio.Operating Temperature: 50 °F – 104 °F (10 °C – 40 °C)",
      "Viewing Angle is 178° (H) / 178° (V); Aspect Ratio is 32:9",
      "Samsung QLED delivers purer, brighter, and more lifelike colors",
      "Hdr (high Dynamic Range) technology",
      "Smoother gameplay with fast 144Hz refresh rate and has Stand",
      "Designed for gamers with multiple game modes. Swivel--2.0° (plus/minus 2.0°) to plus 15.0° (plus/minus 2.0°)",
    ],
  },
  {
    id: 15,
    images: [
      "https://m.media-amazon.com/images/I/81kOjKzKnvL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Go0wjeIgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/7151vUX4bTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81fSTbGR4TL._AC_SL1500_.jpg",
    ],
    details: [
      "3 In 1 Jacket Design: 3 in 1 womens ski jacket for all weather conditions. The shell can be as a windbreaker in spring and autumn. The upper part of the liner is spliced with windproof fabric, fashionable，comfortable and warm to wear alone in late autumn. The shell and fleece liner can be combined to fully seal to prevent cold in frost winter",
      "Waterproof Protection: The womens ski jacket made of excellent waterproof fabric which values 5000mm H2O. It is fully sealed to prevent water and stain from seeping inwards so that let you easily deal with outdoor rainstorm climate calmly",
      "Windproof Design: Featured a detachable hood with hook and loop and an adjustable drawstring, adjustable cuffs, wind-blocking placket zipper, inner jacket elastic drawstring cuffs and stand collar designed keeping you protected from warmth and protection for your winter travel",
      "6 Pockets: 3 in 1 women jackets great as sport work jackets as well as casual jackets. The shell has 2 hand zippered pockets, The outside pockets are all waterproof zippers to prevent your personal belongings from getting wet. Inner fleece jacket have 2 pockets on inner, 2 hidden pockets inside inner to meet your daily storage needs, easy to hold valuables and other accessories",
      "Perfect for Winter Activities: Ski jackets with excellent waterproof is perfect choice for all winter activities. Such as skiing, climbing, hiking, cycling, trekking, mountaineering, snowboarding, tourism, camping",
    ],
  },
  {
    id: 16,
    images: [
      "https://m.media-amazon.com/images/I/71maQ4MGfYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81RTX9eymaL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91hlvLZGNHL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71PLkSqmvsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71+CyBHlM7L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81lUQjRNkyL._AC_SL1500_.jpg",
    ],
    details: [
      "Faux leather material for style and comfort / 2 pockets of front",
      "2-For-One Hooded denim style faux leather jacket",
      "Button detail on waist / Detail stitching at sides",
      "HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
      "Please check the size chart below to ensure your order / Color Disclaimer : Due to monitor settings, monitor pixel definitions, we cannot guarantee that the color you see on your screen as an exact color of the product. We strive to make our colors as accurate as possible. however, colors are approximations of actual colors.womens motocrycle jacket",
    ],
  },
  {
    id: 17,
    images: [
      "https://m.media-amazon.com/images/I/71pewia-KXS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61oELWSsE3S._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61WloTnyyeS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/712DDhZBsXS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71ypZ2cpc0L._AC_SL1500_.jpg",
    ],
    details: [
      "【Waterproof Rain Jacket keep you dry all the time】---Suitable for your hiking,climbing,traveling,camping,sport outdoor,easy to quick-drying when it is light rain or snow and wind.",
      "【Lightweight perfet for trip or casual wear】---Rain Jacket Womens Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 3 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
      "【Hooded detachable and Functional pocket 】---Lightweight Rain Jacket is detachable hood,you can wear it when it is raining or big wind or as a fashion element.you can remove the hooded to have a simple raincoat.",
      "【Stylish Striped Linning Design】---Rain Jacket Womens Waterproof with Hood is made of 100% Polyster so it is not strechy, but runs a little big, you can wear t-shirt or sweater inside",
      "【Women Raincoats Garement Care】---Hand-wash, Dry Clean, Do not machine wash, Machine wash easily damage the waterproof fabric. Please Refer to Our Size Chart in Product Description (Not the Amazon size chart)",
    ],
  },
  {
    id: 18,
    images: [
      "https://m.media-amazon.com/images/I/71z3kpMAYsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/817cdkiSn4L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71lOkDyEnLL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81gF6aFvMIL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71kD5ggtKyL._AC_SL1500_.jpg",
    ],
    details: [
      "Lightweight fabric / Assorted colors",
      "A rayon blend tunic featuring a trapeze fit and flare fit",
      "Along with a rounded scoop neckline and classic long sleeves",
      "Hand Wash Cold / No Bleach / Lay Flat Dry",
      "Please check the size chart below to ensure your order / Color Disclaimer : Due to monitor settings, monitor pixel definitions, we cannot guarantee that the color you see on your screen as an exact color of the product. We strive to make our colors as accurate as possible. however, colors are approximations of actual colors.",
    ],
  },
  {
    id: 19,
    images: [
      "https://m.media-amazon.com/images/I/51eg55uWmdL._AC_SL1500.jpg",
      "https://m.media-amazon.com/images/I/71asFB1x3PL._AC_SL1500_.jpg",
    ],
    details: [
      "Super soft comfortable & highly breathable",
      "Lightweight, roomy with moisture wicking fabric which helps to keep moisture away",
      "Very Soft to the touch Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek more feminine silhouette and added comfort",
      "Advanced Technology Conducts Heat And Sweat Away and evaporates moisture from Your Body fast",
      "Can run a little small. If you typically find yourself in-between sizes and you prefer a more loose fit, please consider the larger size. Gently contoured silhouette",
    ],
  },
  {
    id: 20,
    images: [
      "https://m.media-amazon.com/images/I/61pHAEJ4NML._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61SV1eGaqsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91hFRqkJHpL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61oA1-b8XpL._AC_SL1500_.jpg",
    ],
    details: [
      "If you like loose style, please buy one size up.",
      "Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees",
      "The fabric is soft and has some stretch.",
      "Occasion: Casual/Office/Beach/School/Home/Street.",
      "Season: Spring,Summer,Autumn,Winter.",
    ],
  },
];

export const PRODUCT_PRICES = [
  { productId: 1, price: 109.95 },
  { productId: 2, price: 22.3 },
  { productId: 3, price: 55.99 },
  { productId: 4, price: 15.99 },
  { productId: 5, price: 695 },
  { productId: 6, price: 168 },
  { productId: 7, price: 9.99 },
  { productId: 8, price: 10.99 },
  { productId: 9, price: 64 },
  { productId: 10, price: 109 },
  { productId: 11, price: 109 },
  { productId: 12, price: 114 },
  { productId: 13, price: 599 },
  { productId: 14, price: 999.99 },
  { productId: 15, price: 56.99 },
  { productId: 16, price: 29.95 },
  { productId: 17, price: 39.99 },
  { productId: 18, price: 9.85 },
  { productId: 19, price: 7.95 },
  { productId: 20, price: 12.99 },
];
